# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mgonzaga <mgonzaga@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/03 19:02:20 by mgonzaga          #+#    #+#              #
#    Updated: 2024/12/03 19:10:52 by mgonzaga         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = phone_book
CFLAGS = -Wall -Werror -Wextra
COMPILE = c++ -std=c++98


CPP = $(wildcard *.cpp)
HPP = $(wildcard *.hpp)

all:
	$(COMPILE) $(CPP) $(CFLAGS) -o $(NAME)
